name: Gamemode
version: 2.0
main: de.eintosti.gamemode.Gamemode
author: einTosti
website: www.twitter.com/einTosti

commands:
    gm:
      description: Easily change your Gamemode.
      usage: /<command> <0,1,2,3>
      alias: [gamemode]
    gmc:
      description: Changes your Gamemode to creative.
      usage: /<command>
    gms:
      description: Changes your Gamemode to survival.
      usage: /<command>
    gma:
      description: Changes your Gamemode to adventure.
      usage: /<command>
    gmsp:
      description: Changes your Gamemode to spectator.
      usage: /<command>

permissions:
    gm.colour:
        description: Allows you to change the colour of the messages
        default: OP
    gm.creative:
        description: Allows you to change your gamemode to creative
        default: OP
    gm.survival:
        description: Allows you to change your gamemode to survival
        default: OP
    gm.adventure:
        description: Allows you to change your gamemode to adventure
        default: OP
    gm.spectator:
        description: Allows you to change your gamemode to spectator
        default: OP
    gm.setothers:
        description: Allows you to change the gammeode of other players
        default: OP
    gm.info:
        description: Tells you information about the plugin
        default: true
    gm.notify:
        description: Get notified if there is a new version available
        default: OP